config.rb requires methods from util.rb
```
.../lib/sup/config.rb:60:in `load_config': undefined method `fix_encoding!' for "<user>":String (NoMethodError)
	from .../bin/sup:13:in `<top (required)>'
	from .../bin/sup:22:in `load'
	from .../bin/sup:22:in `<main>'
```